{% set version = "0.6.2" %}

package:
  name: pyjulia
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/j/julia/julia-{{ version }}.tar.gz
    sha256: 35eefc030671392b79ba0e1898b7103ed1286ad044783c4cadc99d4401c368e3

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<4.0
    - julia >=1.5.0

test:
  imports:
    - julia
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -c 'import julia; julia.install(); from julia.core import Julia; Julia(compiled_modules=False); from julia import Main'

about:
  home: https://github.com/JuliaPy/pyjulia
  license: MIT
  license_file: LICENSE.md
  summary: An interface to the Julia language from Python
  doc_url: https://pyjulia.readthedocs.io/en/latest/
  dev_url: https://github.com/JuliaPy/pyjulia

extra:
  recipe-maintainers:
    - MilesCranmer
    - ngam
    - mkitti
