{% set version = "0.6.1" %}

package:
  name: pyjulia
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/j/julia/julia-{{ version }}.tar.gz
    sha256: dbada3b47cb14b3e1893dae8339053e014cf09f8158f408b6a129ca4dfca1f61

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4.0
    - pip
  run:
    - python >=3.6,<4.0
    - julia >=1.5.0

test:
  imports:
    - julia
  requires:
    - pip
  commands:
    - pip check
    - python -c 'import julia; julia.install(); from julia.core import Julia; Julia(compiled_modules=False); from julia import Main'

about:
  home: https://github.com/JuliaPy/pyjulia
  license: MIT
  license_file: LICENSE.md
  summary: An interface to the Julia language from Python
  doc_url: https://pyjulia.readthedocs.io/en/latest/
  dev_url: https://github.com/JuliaPy/pyjulia

extra:
  recipe-maintainers:
    - MilesCranmer
    - ngam
    - mkitti
